language: node_js

stages:
  - name: script
    if: branch = main

script:
  # Test a production build on PR builds and main merges
  - yarn build:prefix

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./public
  on:
    branch: main
